### ISSUE TITLE
Update to GCC 7

### ISSUE THREAD

**Issue by Jmgr** [bebbo/amiga-gcc#217] opened 2021-04-24 12:19 UTC
Would it be possible to update to GCC 7? I would like to use `string_view` but that has only been added since that version of the compiler's libraries.

**Comment by bebbo** [comment] 2021-04-24 13:12
it is definitely possible to port this to gcc 7. You just have to find someone to do it.

**Comment by glebm** [comment] 2021-04-24 13:29
Any idea on the amount of effort to do such a thing?
I have a feeling it may not be a simple git rebase + some conflict resolution...

**Comment by glebm** [comment] 2021-04-24 14:10
Also I guess if upgrading anyway, might as well go for GCC 10?

**Comment by bebbo** [comment] 2021-04-24 15:35
> Also I guess if upgrading anyway, might as well go for GCC 10?

gcc 10 for amiga already exists on my drive and you can test the code quality of it here: https://franke.ms/cex/z/8nGE5r

**Comment by glebm** [comment] 2021-04-25 12:21
I can't read m68k assembly. Do you mean that GCC10 asm is less optimal?
Is there a corresponding bug on the GCC issue tracker?

**Comment by glebm** [comment] 2021-04-25 12:30
Some background on this: This is for the DevilutionX port, which is currently undergoing some refactoring and modernization of the codebase. We'd like to use libraries that require C++17, as well as use C++17 in DevilutionX's code.

This will help Amiga as well, e.g. one of these C++17-only libraries allows us to enable audio streaming.

Perhaps there is a GCC10 Docker container we can use to produce Amiga builds, even if it's slower than GCC6? I'd really like to not drop Amiga support but at the same time we can't be stuck on ancient GCC forever.

**Comment by bebbo** [comment] 2021-04-25 16:58
> I can't read m68k assembly. Do you mean that GCC10 asm is less optimal?

It's possible that there are cases where gcc10 yields better code than gcc6. My point is that I added additional optimzations to the gcc6 Amiga version, so gcc-6.5.0b generates better code than the stock gcc-6-5.0.

Thus, yes: gcc-10 code is worse than gcc-6.5.0b's code.

> Is there a corresponding bug on the GCC issue tracker?

No, since it's not a bug (once I opened an issue including the solution... guess what...)
So considering the conversations I had in the gcc-help@gcc.gnu.org channel: The probability that any of my changes will be accepted is less than zero.

**Comment by bebbo** [comment] 2021-04-25 17:06
> Some background on this: This is for the DevilutionX port, which is currently undergoing some refactoring and modernization of the codebase. We'd like to use libraries that require C++17, as well as use C++17 in DevilutionX's code.

Everyone must make their own decisions.
 
> This will help the Amiga port as well, e.g. one of these C++17-only libraries allows us to enable audio streaming.

The Amiga people are certainly happy about every improvement.

> Is there a GCC10 Docker container that we can use to produce Amiga builds, even if it's slower than GCC6? I'd really like to not drop Amiga support but at the same time we can't be stuck on the subset of features supported by an ancient GCC forever.

Not that I know of. But I don't know much either.

**Comment by bebbo** [comment] 2022-05-15 06:27
won't fix

**Closed by bebbo** 2022-05-15 06:27 UTC
Labels: won't fix
