### ISSUE TITLE
Read only data sections are intermixed with code sections

### ISSUE THREAD

**Issue by michalsc** [bebbo/amiga-gcc#46] opened 2018-09-27 13:50 UTC
With current gcc the .rodata sections of generated files are intermixed directly with .text sections. This is not a behavior observable in case of other platforms and it may result in an executable which does compile properly but crash at startup.

Given the source code:

#include <exec/types.h>
const UWORD bad_data = 0x4afc; // ILLEGAL m68k opcode
int function() {
    return -1;
}

Compile with options -nostdlib -noixemul. Resulting executable will contain the bad_data placed **before** the function body in executable section. Thus the file will crash when executed on Amiga.

The .rodata sections should be all passed **after** executable sections. At least this is the way it work on all other platforms. If any specific data shall be put into executable section, it shall be done with __attribute__((section(".text"))) instead.

**Comment by tehKaiN** [comment] 2018-10-18 20:57
So why that's a "won't fix"? As a less experienced programmer I'm a bit confused and worried that such simple thing as declaring a constant before function may cause crashes in my apps. If it's that hard to fix, how does one protect from such unexpected behavior?

**Comment by bebbo** [comment] 2018-10-19 19:53
It's a good feature to put const data into the text (code) section, since it allows pcrel addressing.
For the rare cases providing an own startup code you can spend the few bytes to add a ```bra __entrypoint``` as first insn.

Tiny effort for folks with own startup.
Way less effort for me.
Good!

**Closed** 2018-10-22 07:35 UTC
Labels: wontfix
